### ISSUE TITLE
use paragraph in  list

### ISSUE THREAD

**Issue by istiaqiut** [trade-informatics/caracal#100]
Hi @jdugan 
Hope you are doing well.
 Is there a way to genereate the following output
```
1. Name:
Biography:
2. Name
Biography
```
I have tried the following way-
```
Caracal::Document.save '/user_list.docx' do |docx|
 docx.ol do
   @user.each do |user|
     li user.name
     docx.p user.biography   
    end
 end
end
```
which outputs the following:
```
user1 Biography
user2 Biography
1. user.name1
2. user.name2
```
 
Can you please help in this regard?

Thanks.

**Comment by jdugan** [comment]
There's an example of what you want to do (or, at least, the closest Carcal can get) in the example project [here](https://github.com/trade-informatics/caracal-example/blob/master/app/views/examples/show.docx.caracal#L195).

In Word, list items are really just paragraphs with special styling.  This relationship is mirrored in Caracal, so you'll notice that `li` blocks take all the same commands as `p`.  In Caracal blocks, you can think of `text` commands as being roughly analogous to `<span />` tags.  So, in the example, the first `text` runs right up to the numbering; then you need a `br` to get a line feed; the next `text` will be aligned with the first one.

Something more like the following should work:
```ruby
docx.ol do 
  @users.each do |user|
    li do
      text user.name
      br
      text user.biography
    end
  end
end
```

**Comment by istiaqiut** [comment]
Thanks.
Does this p or li tag accept img and table tag?

**Comment by jdugan** [comment]
The easiest way to answer questions like these is to look at the source code.  By looking at the `ListItemModel` [sub-methods](https://github.com/trade-informatics/caracal/blob/master/lib/caracal/core/models/list_item_model.rb#L57), you can see what is supported.  Here, because `ListItemModel` subclasses `ParagraphModel`, you need to look at [its sub-methods](https://github.com/trade-informatics/caracal/blob/master/lib/caracal/core/models/paragraph_model.rb#L93), too.

So, the answer is no, it doesn't allow that.  The reason is that HTML idioms do not translate directly to Word.  Some actions that your browser will allow have no corresponding OOXML syntax.  There are limitations to the analogy.  

`TableCellModel`s do allow a wide variety of inner commands, including images, other tables, custom widths/margins, and, of course, text.  So, given that you're trying to render relatively complex formatting, you might be better off structuring this as a borderless table and controlling the numbering yourself by looping the recordset with an index.
