### ISSUE TITLE
cell_style bold option is not wroking.

### ISSUE THREAD

**Issue by boostbob** [trade-informatics/caracal#20]
```
cell_style cols[0], bold: true, color: 'aaa'
```

the cell text show as normal font, not bold style.

**Comment by jdugan** [comment]
I updated the README to include a link to a an example repo.  That repo is a simple Rails project that demonstrates most of Caracal's features, including cell styling by column.  The feature definitely works for the versions of Word I can check from my machine.

My guess is Word is ignoring your text styling because you passed in a 3-char RGB value.  I don't believe Word is capable of expanding `aaa` to `aaaaaa` like your browser will.  Try providing the full 6-char hex value.

**Comment by boostbob** [comment]
thank you for you reply, i will try it with `aaaaaa` mode.
