### ISSUE TITLE
Image cannot be displayed

### ISSUE THREAD

**Issue by omaralkaisy** [trade-informatics/caracal#27]
Hi, I have an issue with displaying images. This works:

docx.img 'http://www.anexternalwebsite.co.uk/images/logo.gif', width: 200, height: 60

however this doesn't:

docx.img 'app/assets/images/logo.gif', width: 200, height: 60

The path is recognised, and the doc is generated, but the image is displayed in the doc with a cross and "This image cannot currently be displayed."

Any help much appreciated! Great gem by the way!

Omar

**Comment by jdugan** [comment]
Word documents embed images inside them and keep a sort of index of those assets.  

When you provide an external url, Caracal uses Net::HTTP to read the data, save its data to a file, and index the embedded file via the supplied URL.

If you want to use a local file, you can do that, too, but the options signature is a bit different.  Since Caracal can't use Net::HTTP to read the local file data, you'll need to do that yourself and pass Caracal the base64 data explicitly.  You can use ruby's built-in `File` library to read the image content into a string and then use the `Base64` library to encode the raw string into format that can be written into Caracal's ZIP file.  As the README notes, you still want to provide the local path to the file in the `img` call, as this gives Caracal something to use when it indexes the resulting embedded file.

Without testing this pseudo-code at all, you'll want to do something like the following:

```ruby
img_data = Base64.encode64( File.read('public/logo.png') )
docx.img 'public/logo.png' do
  data    img_data
  width   200
  height  60
end
```

OR, since this looks like a Rails asset, you should be able to use the built-in Rails url helper to get a fully-qualified URL for all environments like so:

```ruby
docx.img image_url('logo.png'), width: 200, height: 60
```

**Comment by omaralkaisy** [comment]
Hi, and thanks for your reply. I have tried various ways of the above, but I still get the same issue. Again, if the file.read path is wrong, it fails, so the issue is not with that. Any further ideas please?

Thanks again!

Omar

**Comment by jdugan** [comment]
Sure.  

Huh, that's strange.  Reading the data works totally fine for me.  Tell you what.  I'll reopen the issue and  add a working piece of code to the example project (https://github.com/trade-informatics/caracal-example).  Then you can try running that locally.  Maybe there's just something going on here with your particular flavor of OS and Word.

The example code in question is here: https://github.com/trade-informatics/caracal-example/blob/master/app/views/examples/show.docx.caracal#L21

**Comment by omaralkaisy** [comment]
Thanks again. I downloaded the .png and put into the public folder, then copied those 2 lines to my project i.e.

data = Base64.encode64(File.read('public/plia-login.png'))
docx.img 'public/plia-login.png', data: data, width: 400, height: 124, align: :right

and I still get the same issue. I'm running Windows 7 SP1, MIcrosoft Office 2010.

**Comment by jdugan** [comment]
If you'll humor me, please clone the example project and do all the normal bundle and rake tasks to set it up.  (It has very, very few dependencies.)  Then start it with webrick and go to http://localhost:3000/example.

I concede that what you've done is reasonable, but I have no idea what else is going on inside your rails project.  The example project is designed both to demonstrate many of the things Caracal can do but also to give developers a known working project to test for local environment/version issues.

If you still see a broken image, please find the downloaded .docx file and change the extension to .zip.  Then expand the file.  Is the image created from the data string valid on your file system?  Do you see something like this?

![screen shot 2016-01-26 at 12 19 42](https://cloud.githubusercontent.com/assets/34268/12590237/7fa51b4c-c427-11e5-996b-27b111a0b904.png)

Part of why I'm confused is this feature has been stable for a long time and the original version of the library was tested on MSWord 2010.  In any event, the feature works as expected on OSX and Ubuntu with MSWord 2010.

**Comment by omaralkaisy** [comment]
Hi John, and thanks again for your help. I notice that the example is rails 4, whereas I am on rails 3.2. Any suggestions pls?

Thanks

Omar

**Comment by jdugan** [comment]
What was the result of running the example project (rails 4.2.5.1; ruby 2.1.8) on your local environment?  

The first step to debugging your problem is determining whether or not you see the broken image behavior with a verified, working Caracal example.  I won't be able to offer you any advice until I know the result of that test.

**Comment by omaralkaisy** [comment]
Sorry what I mean to say is, I don't have Rails 4 installed, only Rails 3.2, will this example work on 3.2? If so I will try this weekend!

**Comment by jdugan** [comment]
`caracal-rails` certainly works fine in Rails 3.2, but if you run bundler on the example project, it will install the specified version of Rails for you.  That's what bundler is for. :)  

Again, the very first thing I'd like you to test is whether you get aberrant behavior using the verified example case for Caracal using the exact versions of Ruby and Rails that the example case specifies.  Because the example project is a **known, proven working case**, if you run it as is and still have a problem, that will suggest fairly strongly that what you are seeing is not an issue with Caracal per se.  (In that case, you would probably have some issue with another gem that requires native extensions, likely `rubyzip`.)

Ideally, I'd like you to test the caracal example on your machine for 4 cases:
- Rails 4.2.5.1, Ruby 2.1.8
- the exact version of Rails your project specifies, Ruby 2.1.8
- Rails 4.2.5.1, the exact version of Ruby your project specifies
- the exact version of Rails your project specifies, the exact version of Ruby your project specifies

You can do this by adjusting the values in the `Gemfile` and `.ruby-version` files in conjuction with bundler and rvm (or rbenv, etc).

That would probably be enough information to get some sense of where things are going wrong for you locally.

**Comment by omaralkaisy** [comment]
Hi John, I can't seem to bundle install this example. I am getting issues with nokogiri and kgio:

Installing nokogiri 1.6.7.2
Invalid gemspec in [C:/RailsInstaller/Ruby1.9.3/lib/ruby/gems/1.9.1/specificatio
ns/nokogiri-1.6.7.2-x86-mingw32.gemspec]: Illformed requirement ["< 2.3, >= 1.9.
2"]

An error occurred while installing kgio (2.9.2), and Bundler cannot continue.
Make sure that `gem install kgio -v '2.9.2'` succeeds before bundling.

Any ideas? I notice that it is using the existing C:/RailsInstaller/Ruby1.9.3 path, which I assume can't be right...

Thanks

Omar

**Comment by jdugan** [comment]
Truthfully, I don't know anything about Rails Installer.  (I manage my ruby and rails environments myself.)  I suspect your installed environment can't handle multiple rubies and is trying to bundle install on whatever version of ruby came with it...but you'd have to consult the documentation for Rails Installer and contact that team for help there.  Or maybe try Stack Overflow.

I'm happy to assist here with Caracal-specific issues, but this is getting well outside those boundaries.  If you get your local environment in order and have a chance to complete the tests described above, please feel free to circle back then.

**Comment by jdugan** [comment]
Closing this as I believe it is likely just a local install issue.

**Comment by istiaqiut** [comment]
Hi John,
What will be the URL when I need to show an image from database?

**Comment by jdugan** [comment]
If you provide the raw image data to the `img` method, the URL value can really be anything you want.  Caracal only uses the value as an index for the object in an ancillary mapping that Word requires.  (The requirement is a bit of a hack, really.  Caracal should probably just generate some value in this case--but I am but one man!)

**Comment by istiaqiut** [comment]
I am giving this
docx.img '#{user.picture.path}', width: 200, height: 60

It gives me this error- No such file or directory @ rb_sysopen - #{user.picture.path}

**Comment by jdugan** [comment]
Ah.  So, under the hood, Caracal uses Net::HTTP to resolve and read img data provided as a URL.  Here, your system seems to be trying to read a local file path.  Net::HTTP cannot read your file system.  To give Caracal local file data, you'll need to read the img using ruby's `File` module and pass the resulting data directly.

There's an example of how to do this in the Caracal example project noted at the top of the README.  (The very first image in the example project's output file is read using the `File`.)

**Comment by istiaqiut** [comment]
I have seen it.
Now I am trying in this way. Still no luck.
data = Base64.encode64(File.read('user.picture.url'))
docx.img 'user.picture.url', data: data, width: 400, height: 124, align: :right

**Comment by jdugan** [comment]
Here, you're getting an error because you are passing the string 'user.picture.url' to `File.read` instead of the value contained in the variable `user.picture.url`.

That's just a straight-up ruby syntax error.  :)

**Comment by istiaqiut** [comment]
It would be great if you can show me a demo.
Thanks

**Comment by jdugan** [comment]
I guess that's what I was trying to indicate earlier.  The example project mentioned in the Overview of this library's README *is* a demo of nearly every Caracal feature.

https://github.com/trade-informatics/caracal-example

**Comment by istiaqiut** [comment]
Thanks a lot.
It worked finally.

**Comment by originalusername123** [comment]
Hello!

First of all, I can't thank you enough for creating Caracal, it's currently saving me a lot of time and work. When I learn a little more coding I'll try to address the footnotes issue, which is the only thing missing for me (and maybe the image in the header).
For now,  I'm having the same issue as described here. Even though I'm following the exact same formula described in the caracal example for adding a local image, I get the "the picture can't be displayed" error. Here's what I do:
```
require 'base64'
data = Base64.encode64(File.read('C:\Users\myself\desktop\AC\lib\image.png'))
docx.img 'C:\Users\myself\desktop\AC\lib\image.png', data: data, width: 400, height: 124, align: :right
```
It is the exact same way that is shown in the example. However, it doesn't work for me. I know it's not that it doesn't find the file, so I really don't know how to solve this. Please help! Thank you!

**Comment by jdugan** [comment]
Hi, @originalusername123.  Thanks for the kind words!

I don't think this is exactly the same issue, largely because the previous poster simply had a number of ruby syntax errors in his/her code and your code seems to be valid.

The way the image renderer works is it prefers the named `data` argument over the unnamed `url` argument in the first position.  (This interface is a little hackish and not my favourite part of Caracal.  Images need an url-like parameter in order to be entered in an internal Word registry for assets and to reliably determine the extension/mime type of the asset.  This is one, admittedly clunky, way to resolve [that requirement](https://github.com/trade-informatics/caracal#images).)  


Anyway, what that means is if you provide a non-blank value to data, that value is what Caracal renders; if not, Caracal uses Net::HTTP to read in the image found at the url location.

In your case, I would check three things, in this order:

1.  I know it sounds simple, but the first thing I'd check is that your `data` variable actually has a value.  I suspect it does because I don't think you would get a rendered document if Net::HTTP tried to read a local file.  But it's always good to verify each step of the process to be certain where things are breaking down.

2.  So, the way Word works is it actually copies your image content and embeds it inside the document.  If the data variable looks okay to you, I'd encourage you to crack open the file Caracal created. (You do this by changing the .docx extension to .zip and extracting the archive.) Then check the `word/media` directory.  Your image will have a programmatically determined name, but the content will be unaltered.  Is your image in this directory and can you open it?  Does it have the right file extension?  Or is the data corrupted in some way?

3.  It's possible that the full file path you've provided in the first argument might be causing Word difficulties.  I don't have any reason to think this is true other than intuition, but it is conceivable to me that the asset registry might break if an item's key is a full path.  You might try changing the first argument to `docx.img` something simpler and more url-esque like `lib/image.png` and see if that helps.

**Comment by originalusername123** [comment]
Hi John!

Thanks for your detailed answer! I checked the three things, here they are, in order:

1. I checked if it has data, it does, although it's a very short string, in particular ` iVBORwo=`. Is that a valid value that it could have, or is there some kind of error there?

2. I checked this, and the file exists, for some reason under the name "image7.png". But when I try to open it in the "Photos" app in Windows (the default one), it shows "it looks like we don't support this file format".  I thought that maybe the PNG was the problem, so I tried this time with a JPG. Same result (though the string from base64 was considerably longer) but different message, now it says "We can't open this file". So yes, I think the file maybe corrupt at this point.

3. Changed it as you said, nothing changes.

Any ideas on what maybe wrong? 

Thank you very much!

**Comment by jdugan** [comment]
1.  Oh, no, that is 100% not a reasonable value for an image file.  What you're doing in that step is reading in the data that comprises the image and then encoding it as a string (to make it safer to pass around).  Even for a small image, this should be a sizeable string.  Whatever is going wrong for you is in the step where you're reading in the file.  This isn't a Caracal issue at all.  Everything else you described suggests Caracal is doing exactly what it should do.

I don't use a Windows machine, but I googled around your issue a bit and it looks like Windows requires you to open the files in binary mode explicitly.  Something more like this:

```ruby
data = File.open('C:\path\to\your\image.png', 'rb').read
```

**Comment by jdugan** [comment]
Sorry, you still need to Base64 encode the data.

**Comment by originalusername123** [comment]
Ok, final code looks like this:

```
require 'base64'
data = File.open('lib\image.jpg', 'rb').read	
finaldata = Base64.encode64(data)
print "The content of finaldata is #{finaldata}"
docx.img 'lib\image.jpg', data: finaldata, width: 300, height: 300, align: :right
```
And now the content of 'finaldata' is a few pages string of readable characters. However, the final outcome is the same. Checked, and the file is still corrupt inside =(.

**Comment by jdugan** [comment]
Huh.  I feel a little hamstrung here since I haven't had a Windows environment in almost 15 years.  Can you make a public project on Github that demonstrates your issue?  I guess I'd like to verify whether or not your code has a problem in a *nix environment.  The best I can tell you right now is the feature absolutely works for me and countless other folks.  So, whatever is going on is a tractable problem. :)

Side note:  Does the [caracal-example](https://github.com/trade-informatics/caracal-example) project produce a sensible result for you on Windows?

**Comment by originalusername123** [comment]
Hello! Ok, I will find out how to create a public project.

I tested the caracal-example and it works great, except for the part of the local file =O. I'll let you know as soon as I create the project, will make it as simple as possible.

**Comment by omaralkaisy** [comment]
Hi


Actually there was nothing wrong with the code, there were no errors as John says. The original issue I posted was:


This works:

docx.img 'http://www.anexternalwebsite.co.uk/images/logo.gif', width: 200, height: 60

however this doesn't:

docx.img 'app/assets/images/logo.gif', width: 200, height: 60

I never got to the bottom of the issue in Rails 3.2, however when I upgraded to Rails 4 then 5, it worked fine. Hope you have better luck!


Thanks


Omar


________________________________

**Comment by originalusername123** [comment]
Hi omaralkaisy!

I have trouble with embedding a local image too. **I'm not using Rails, by the way, just Ruby**, I just realized I haven't been specific about this.

**Comment by jdugan** [comment]
FWIW, the code errors to which I referred were related to the most recent round of questions on this thread rather than Omar's original question.  He, like you, was (mostly) having environment-specific issues related to running Caracal on a Windows machine.

I wasn't confused about you running Caracal outside Rails.  The `img` command is a feature that has always existed in Caracal and works 100% of the time on Unix/Linux systems.  Your issue is clearly related to how Caracal's dependencies read/write data on your Windows filesystem.  The fact that you see a broken image in the Caracal example project--which is a kind of canonical implementation of the library--confirms that pretty conclusively.

There are really only two possibilities here that make sense to me:
1. Your machine is converting the image to base64 incorrectly; or
2. Rubyzip is writing the base64 data to your filesystem incorrectly.

Since (if I understand correctly) you can see the remote images in the output of the Caracal example project, I think it makes sense to focus on possibility #1.  

I made a [gist](https://gist.github.com/jdugan/2506d254d9fde48d2eb55992c65dc956) this morning that shows you what the correct output values are for an image we can both download and use.  I'd ask you to follow the procedure in the gist and verify that you get the exact same result for each step.
