### ISSUE TITLE
Helper methods not supported?

### ISSUE THREAD

**Issue by olimart** [trade-informatics/caracal#29]
Hi,

the following raises ```undefined method `formatted_question' for #<Caracal::Core::Models::ParagraphModel:0x007fa98558e018>```

```
docx.p do
    text formatted_question('AAA')
    text ' : '
end
```

my `formatted_question` comes from helper. I'm using `caracal-rails`. Any idea?

**Comment by jdugan** [comment]
They are but not within the context of a `caracal` model.  Said differently, the library doesn't try to pass view context downward recursively through all of its objects.  To achieve what you want, simply assign the result of `formatted_question` to a variable in the view's scope, where that method is understood.  

Something like this should work because you'd just be passing an object (here, a String) via the block:

```ruby
fq = formatted_question('AAA')
docx.p do
  text fq
  text ' : '
end
```

If you need to format a lot of information inside a `caracal` block, it would probably make more sense to instantiate a view model and use that to produce the formatted content.  Because a view model is just an object,`caracal` wouldn't need any special context to use it.

**Comment by olimart** [comment]
Thanks a lot.

> it would probably make more sense to instantiate a view model and use that to produce the formatted content

Felt that as well when looping through objects

**Comment by jordanmaguire** [comment]
FWIW: The following code works fine:

```ruby
docx.p do |p|
  p.text formatted_question('AAA')
  p.text ' : '
end
```

Notice the `|p|` makes all the difference.

It's worth noting that I run my caracal models from within a `lib/` class (not a view). That shouldn't really effect the context I think.
