### ISSUE TITLE
list_style not working?

### ISSUE THREAD

**Issue by a-macnamara** [trade-informatics/caracal#40]
I'm trying to replicate an existing Word template, and I'm having trouble making list_style work. I run the following code at the top of my view:

```
docx.list_style do
	type	:ordered
	level	0
	format	'decimal'
	value	'%1.'
	align	:both
	indent	1440
	left	720
end
```

But it seems to get messed up somewhere in the middle. The document it produces has the line wrap correct (the "marker" seems to go at 0.5" from the margin while the first line of the list item begins at 1" from the margin; subsequent lines of text wrap to 0" from the margin), but the _marker itself does not appear in the generated document_.

The relevant section of the numbering.xml document reads:

```
	<w:abstractNum w:abstractNumId="0">
		<w:nsid w:val="58A1624D"/>
		<w:multiLevelType w:val="multilevel"/>
		<w:tmpl w:val="5F7E016C"/>
		<w:lvl w:ilvl="0">
			<w:numFmt w:val="none"/>
			<w:lvlText w:val=""/>
			<w:lvlJc w:val="left"/>
			<w:pPr>
				<w:tabs>
					<w:tab w:val="num" w:pos="360"/>
				</w:tabs>
			</w:pPr>
		</w:lvl>
```

As you can see, the numFmt element gets defined as "none" and the lvlText gets a blank string. I'm not an expert at Ruby but looking through the caracal code, it seems that maybe the data structure isn't being filled properly with the list_styles command I entered?

(Also, curious to note that the documentation suggests 'left' should be > 'indent' but when I set it as above, the indentation seems correct as I've described.... It's a good bit different than the numbering.xml produced by Word, which has a w:ind element with a w:left and w:hanging option that seem to specify the right twips values, so maybe this is just a fluke that Word renders it OK.)

I'll continue to dig, but am I missing something basic here? Any thoughts on how to get this to work?

**Comment by jdugan** [comment]
Thanks for the detailed issue description.  I suspect you're using a newer version of Word (2016?) than existed when Caracal was written, and Word has, once again, changed the way it wants the OOXML formatted.  Every version of Word is essentially a major version release.

What's interesting to me is the XML block you included is *very* different than what Caracal actually produces.  You can see the actual output [here](https://github.com/trade-informatics/caracal/blob/master/lib/caracal/renderers/numbering_renderer.rb#L25).

My guess--and it's just that, a guess--is your version of Word is re-rendering the OOXML when it opens the document.  That's kind of crazy, but not super surprising behavior from MS.

All of which is too say, chances are you're using a version of Word that hasn't been tested throughly.  (Caracal was built against 2010 and 2013.)  And what I suspect you're seeing is a variance in how Word expects the OOXML between versions.  Caracal is essentially an exercise in reverse engineering XML content, so if that's true, the way forward is kind of annoying.  You just read the OOXML documentation and try to produce output that satisfies all the versions that make sense to support.  In the original version of Caracal, I used the OOXML produced by Google Docs as my guide because it was already 2010/2013 compatible and *vastly* smaller than what Word produced.

**Comment by a-macnamara** [comment]
Thanks so much for getting back quickly. I think you are right - I tested things out and the symptom I described above seems to be a result of Word rewriting the document. Sorry for the red herring.

After debugging, the issue that caused Word to rewrite seems to be the inclusion of the "align :both" tag. Caracal passes that tag along to the generated numbering.xml, and it seems Word doesn't like that. When I remove that or change it to "align :left", Word renders the XML as I expect. (I have the Normal style overridden to use align :both, and even when I use align :left in the list style, it still formats as align :both, which is fine with me at this point.)

Not sure if this is expected/known behavior but thought I'd report back as to what was causing my trouble.

(BTW this was tested with both Word 2010 in Windows and the latest Word for Mac 2016; no discernable difference in behavior.)
