### ISSUE TITLE
Ruby question: using params within list block?

### ISSUE THREAD

**Issue by a-macnamara** [trade-informatics/caracal#41]
Apologies for the question more related to ruby scoping, but wondering if you or anyone has come across this in caracal and has a better way of solving it:

In a list block (i.e., the block that gets passed to the list to provide the contents of the list), I cannot use instance variables or local variables that are defined in the scope of the view (e.g., the params[] hash). Hence, I can't easily customize the text that goes into the list blocks.

Example (doesn't work):
```
docx.ol do
  li do
    text "here is a param from the form: #{ params[:name_field] }"
  end
end
```

I'm working around it by defining a global hash containing the customized text outside the list block, then referencing the global hash within the list block. It's an ugly hack but it works.

Example (works but ugly):
```
$gp = {
  :txt => params[:name_field]
}
docx.ol do
  li do
    text "here is a param from the form: #{ $gp[:txt] }"
  end
end
```

I didn't see this addressed in caracal-example. Any other options for something like this?

**Comment by jdugan** [comment]
It can just be a local variable (i.e., no need for global scoping), but this is the canonical way of passing variables...at least for now.

So, internally, when you call a method like `ol`, what you're doing is passing your block into a new model instance that interprets your instructions (often by instantiating more models and passing them blocks).  At that point, Rails no longer has access to the action view context.  That's why it can't understand `params` or instance variables built in the controller.

Caracal works this way because we're not rendering a simple, single template like, say, erb renders HTML.  Caracal has to catalog all your instructions and then loop back over them to generate several templates simultaneously (which are eventually zipped up into a single file).  By the time caracal renders your instructions to XML, your controller context is long gone.

But, as long as you reference local variables in your instructions, ruby will naturally pass that lexical scope through into the block (a la how Javascript closures work) and the variable will be available when Caracal evaluates the expression.

I know that's not intuitively obvious unless you've inspected the internals pretty closely.  This probably warrants its own section in the README.

**Comment by a-macnamara** [comment]
Thanks. I'll try to put together a pull request to add this documentation to the README.
