### ISSUE TITLE
Template rendering example

### ISSUE THREAD

**Issue by fatuhoku** [trade-informatics/caracal#46]
The README hints that caracal can be used to render DOCX templates. My use case is e.g. to take an existing template .docx file that contains placeholders like `$FIRST_NAME$` and replace those placeholders with either text or image data.

How is this done?

**Comment by jdugan** [comment]
No, this is not a use case Caracal is designed to support.  Caracal is a Word document generator.  It is philosophically similar to Prawn.  You use Caracal to *construct* Word documents programmatically.

There may be gems available that do what you described, but that's just not what Caracal does.

**Comment by fatuhoku** [comment]
@jdugan Okay. The README says "template rendering" so I thought Caracal renders docx's from templates.

Caracal is probably better characterised as a EDSL for generating DOCX's but has very little to do with templating technologies like ERB or Mustache.

**Comment by jdugan** [comment]
I believe that's exactly how the library is described in the first section of the README.

With respect, Caracal is exactly the same kind of templating technology as ERB or Mustache.  Or, perhaps a more direct comparison is HAML, which allows for variable insertion inside a custom DSL.  I suspect the reason you don't view Caracal as a template renderer is because you're not using it within a framework that implements Tilt.  (Your "template" is essentially the block you're wrapping in the Caracal document call.)

Let's take Rails as an example.  Because Caracal is integrated with Tilt, you could define a view template named my_example.docx.caracal and as long as the template employs valid Caracal syntax, Rails would understand how to render the contents of your template with Caracal and how to set the content type of the response to an appropriate value.

But, just like you have to write valid HAML in your HAML template, you have to send valid Caracal in a Caracal template.  That's why you can't send a Word document into Caracal and expect it to know what that is.

Does that make sense?
