### ISSUE TITLE
Page Orientation

### ISSUE THREAD

**Issue by swedishpotato** [trade-informatics/caracal#50]
Hello!

I absolutely love the Caracal gem, it is truly awesome!

I have a request. While I can produce a Word document that "looks like" it is in landscape orientation, it still tries to print out as portrait. This means the end users have to make sure they set the printer page orientation manually before printing, which they tend to forget.

Is there any way of setting the page orientation to landscape "properly", rather than the current fiddle I use as follows:

# landscape 

docx.page_size do
  width   16837    # sets the page width. units in twips = 297 mm
  height  11905    # sets the page height. units in twips = 210 mm
end

# portrait

docx.page_size do
  width   11905     # sets the page width. units in twips = 210 mm
  height  16837     # sets the page height. units in twips = 297 mm
end

It would also be great to tell Word that the document to be printed is A4, letter etc.

I'd have a go at this myself, but this is way beyond my competency level! :)

Cheers,

Michael

**Comment by jdugan** [comment]
Hi, Michael.

Thanks for the kind words.  I often tell programmers they should manage an open source library if for no other reason than to receive unexpected praise every now and again. It feels good.  :)

I confess I've never had a personal reason to print a landscape file created with Caracal.  I'm surprised the page size changes aren't enough to convince Word to default to landscape orientation in the printer settings, but then again, it's Word, so maybe I shouldn't be surprised.  I suspect there's some simple OOXML attribute we can set to help communicate our intent.

I like the idea of having a standard list of preset sizes.  Especially because twips is such an absurd unit of measurement.  Let's focus first on getting orientation set properly and then revisit preset sizes afterward.

Even if you don't feel up for implementing the feature (which is fine), you might be able to do some investigation of the OOXML to determine what's missing.  There's a brief description of the reverse engineering process I use to work on problems near the end of the README.  My approach is surprisingly unsophisticated.  Google docs are sometimes more helpful than actual Word documents for spotting small differences because they tend to use vastly simplified OOXML (like Caracal).  I'll try to make time to look into the problem myself this weekend.  If you find something before then, please do let me know and I'll try to confirm.

As a side note, it's a bit of pleasant curiosity to me that Caracal has so many Swedish fans.  Particularly because my wife and I are a bit obsessed with all things Scandinavian.  We've been teaching ourselves (forgive me) Norwegian the past year or so.  We visited Norway and Denmark last summer, and we hope to make it to Sweden some day soon.

**Comment by jdugan** [comment]
I just release v1.0.7 that includes a new `page_size` argument that fixes your immediate issue.

This should do the trick:
```ruby
docx.page_size do
  width       16837        # sets the page height. units in twips = 297 mm
  height      11905        # sets the page width. units in twips = 210 mm
  orientation :landscape
end
```

**Comment by swedishpotato** [comment]
Superb! Works for me! Huge thanks!

Michael
