### ISSUE TITLE
Dynamic Images 

### ISSUE THREAD

**Issue by JuliaDahm** [trade-informatics/caracal#52]
Hi there! I've been trying to echo out dynamic images in a generated doc using Caracal-Rails. I tried doing this like so: 

`docx.img image_url('#{@customer.main_photo}'), width: 300, height: 200, align: 'right'`

and got the error:  "bad URI(is not URI?): http://localhost:3000/images/#{customer.main_photo}"

I tried this: 

`docx.img image_tag(@customer.main_photo), width: 300, height: 200, align: 'right'`

& got this error: 
`No such file or directory @ rb_sysopen - <img src="/system/customers/main_photos/000/000/013/original/Main.jpg?1476818582" alt="Main" />`

Finally tried: 

`docx.img image_url(@customer.main_photo), width: 300, height: 200, align: 'right'`

and got:  "Net::ReadTimeout in Customers#onesheet_doc"

**Comment by jdugan** [comment]
**Quick Response**

In the first example, you used single ticks, which tells ruby to forego string interpolation.  That's why the URI parroted back your ruby syntax.  If you used double ticks, you'd get the same result as the third example.

In the second example, you're formatting an HTML tag, which is a different data type than Caracal expects.

The third example is, IMO, the most idiomatic syntax for your use case.  Here, I suspect you're running into a limitation of Webrick.  Webrick uses a single process.  So when you request the route that produces the document, you consume the process with the request itself.  But your instruction tells Caracal to read a URI.  To do that, it needs to spawn a new process for Net::HTTP.  But it can't do that in Webrick because there's only the single thread.  So, instead, Net::HTTP just sits around waiting for the request process to finish so it can use the one thread.  But that can't happen because the request is the parent of the Net::HTTP call.  Hence, the timeout.


**Suggestions**

The quickest happy path, I suspect, is for you to add unicorn or puma to your Gemfile, configure them with the default values, and use that in development.  That'll give you more than one process for your development server, and you can use the syntax in your third example no sweat.

**Comment by JuliaDahm** [comment]
Thanks for the prompt response! I installed Puma and no longer get an error but now end up with this: 

<img width="1280" alt="screen shot 2016-11-02 at 1 54 40 pm" src="https://cloud.githubusercontent.com/assets/17298336/19941493/abe4b7dc-a106-11e6-930e-e5eda56226e3.png">

The logs check out that everything was rendered properly, so I'm not sure what I'm doing wrong here.

**Comment by jdugan** [comment]
You're welcome.  Hard to say without seeing your controller code, but this is pretty much what I'd expect if the browser tried to render a Word document as HTML.

By default, Rails assumes all routes answer in HTML unless you tell it differently by either (1) restricting the format in the routes file or (2) including an extension in the URI itself so Tilt can auto-map the request to a format handler.

The Caracal example project demonstrates the former strategy.

**Comment by JuliaDahm** [comment]
Forgot to add format: 'docx' to the route. It works perfectly now. THANK YOU THANK YOU THANK YOU!!

**Comment by jdugan** [comment]
No worries.
