### ISSUE TITLE
Image Links

### ISSUE THREAD

**Issue by JuliaDahm** [trade-informatics/caracal#54]
Does Caracal have the ability to display images as links?
I've tried writing this a number of ways and my best guess so far has been: 

`soundcloud_image = image_url('soundcloud-icon.png')
c3 = Caracal::Core::Models::TableCellModel.new do
  img soundcloud_image, width: 60, height: 60
  docx.p do
    link (soundcloud_image), 'https://www.soundcloud.com'
  end 
end

docx.table [[c3]] do
end`

I haven't been able to find anything in the documentation on it. Thanks in advance for your help!

**Comment by jdugan** [comment]
Generally speaking, the README documentation and the [Caracal example project](https://github.com/trade-informatics/caracal-example) are fairly exhaustive in terms of describing what Caracal can do.  If it's not represented in one of those two resources, Caracal probably does not support the feature.

Caracal does not currently support linkable images.  It might be able to do so fairly easily, though.  The main questions are (1) how Word renders images that link to external URIs? and (2) how does that behavior differ from how Word links to internal bookmarks?  

When building a new feature into Caracal, it's important to understand how Word renders the underlying OOXML because that's the only way we can make good decisions about how to model the instructions in a way that can be rendered out as sensible OOXML.  Said differently, while Caracal tries to preserve HTML idioms on principle, there's no guarantee that wrapping a `link` directive around an `img` directive makes sense for Word the way it does for HTML.  Word might expect something very different, e.g., declaring the external URI as a property on the image object itself.

If you're interested in pursuing it further, there's a [short primer](https://github.com/trade-informatics/caracal#how-to-work-on-a-problem) near the bottom of the README that describes how to go about investigating OOXML behavior.
