### ISSUE TITLE
Columns

### ISSUE THREAD

**Issue by rafaelbessoni** [trade-informatics/caracal#57]
Hi. First, thanks for the work you have put on this!

Is there a way to change the number of columns in parts of the text? Suppose I wanted the first paragraph as 2 columns and the rest of the text normal. I am able to achieve a similar effect putting my text inside a table without borders with the desired number of columns, but it isn't quite the same thing.

**Comment by jdugan** [comment]
Thanks, I appreciate that.  I tell colleagues one of the nicest things about managing an open source library is the fairly regular compliments from total strangers.  The positives far outweigh the negatives, in my experience.

There isn't right now, no.  Your workaround is the best Caracal can do without adding paragraph columns as a new feature.

Caracal was written for a project with limited formatting requirements, so the initial feature set is pretty bare bones.  I try to be comprehensive in the README and the example project in terms of describing the library's capabilities, but a good rule of thumb is Caracal has the same feature set as Google docs&mdash;it's squarely down-the-middle in terms of Word features.  Paragraph columns is one of the few Google doc features I know we don't support right now.

I do, however, accept quality pull requests with enthusiasm and gratitude.  If nothing else, I'm an extremely consistent programmer, so once you get the hang of how Caracal is organized, it's obvious how to add a new configuration option.  And, I'm happy to help if you have questions about how best to model/render the new attribute.  There are also a few commits like [this one](https://github.com/trade-informatics/caracal/commit/b6472098eb1d6486b50be33d472e117450b7bacb) that might be helpful in terms of demonstration. (Apologies for all the white space diffs in this commit.)

The basics for contributing are covered in the [README](https://github.com/trade-informatics/caracal#how-to-work-on-a-problem).  I tend to make my sample documents in Google docs because it produces **vastly** simpler OOXML than any version of Word I've tried.
