### ISSUE TITLE
bgcolor Attribute Doesn't Work on Styles

### ISSUE THREAD

**Issue by c0rndogs** [trade-informatics/caracal#58]
If I try to specify a bgcolor attribute for a font style, it does not apply, but if I apply the same attribute to the individual paragraphs within the document, it works fine.

Example:  This applies the font size and font face properly, but not the background:
```
docx.style id: 'code', name: 'Code Excerpt', size: 20, font: 'Consolas', bgcolor: 'eaeaea'
...
docx.p  'Lorem ipsum dolor....', style: 'code'
```
And this applies everything correctly:
```
docx.style id: 'code', name: 'Code Excerpt', size: 20, font: 'Consolas'
...
docx.p  'Lorem ipsum dolor....', style: 'code', bgcolor: 'eaeaea'
```

**Comment by jdugan** [comment]
That's because Caracal doesn't support a `bgcolor` parameter for paragraph styles right now.  :)

The README always has a complete list of accepted parameters for all directives.

It's generally pretty easy to add a single new parameter to an existing model and renderer.  Have you determined what OOXML node controls this for paragraph styles?  My guess is paragraph styles probably use the same xml node as runs (i.e., `w:shd`), but OOXML can be inconsistent about this kind of thing.  It's worth checking.

**Comment by c0rndogs** [comment]
Not yet, I've only recently started tinkering with this, so I'm still digging through all the OOXML stuff (which looks like it might take the rest of my life).  I thought I was just dumb and doing it wrong, glad to know that isn't the case.  I'll see if I can track that node down.

**Comment by jdugan** [comment]
I'm going to close this for now.  You are 100% welcome to send me a pull request, if you still want to add this feature to the library.  I'll remember the conversation without the issue in the tracker.  Cheers!
