### ISSUE TITLE
Allow table rows to span across pages

### ISSUE THREAD

**Issue by jaspertandy** [trade-informatics/caracal#65]
There's an option in word: "Allow row to break across pages" which appears to be enabled by default. I've looked and can't see it, but was wondering if you knew if it was possible to emulate this with the existing toolkit? I have a table that could potentially span multiple pages, so putting a page break before the table isn't going to be enough.

**Comment by jdugan** [comment]
Hi, Jasper.

That's sounds totally reasonable, but as you guessed, that's not something Caracal supports right now.  Because it is a default Word setting, it is probably **very** easy to adjust the underlying OOXML to allow it.  Probably just a single node and/or attribute to render.  The trick, as always, is determining the correct node/attribute to set.

Do you have time to follow the reverse engineering instructions in the README to determine what is happening in the OOXML?  I understand not everyone is up for making a pull request (though that is, of course, welcome and appreciated), but it helps shorten my time investment in new features considerably if the requestor can do the OOXML legwork.

**Comment by jdugan** [comment]
Hei, Jasper.

You no doubt do not care about this issue anymore, but I'm at a hackathon thing tonight in Oslo and thought it'd be a good excuse to squash some Caracal concerns.

I just set up a text in the Caracal example project to make a very long table cell and that rendered across a page break as you'd hoped.  As you suggest, the behaviour is the default in Word, so since Caracal does not restrict it, Word allows the data to flow.

I'm going to close the issue for now since Word seems to handle the case as expected.  If I've misunderstood your issue, please don't hesitate to reopen it.

Cheers!

**Comment by jaspertandy** [comment]
Hi John,

Thanks very much for taking another look at this. I don't even remember which of my projects I was using Caracal for now, but good to know I can come back to it in future if I need to!

Thanks again!
