### ISSUE TITLE
Setting paragraph attributes doesn't affect text

### ISSUE THREAD

**Issue by bolshakov** [trade-informatics/caracal#88]
I'm building document from internal representation, thus DSL is not very convenient for me. Calling `bold`, `bgcolor` and other methods on `ParagraphModel` seems does not work. I wonder, if this API considered public or private?

```ruby 
docx = Caracal::Document.new('test.docx')
paragraph = docx.p('Bold text')
paragraph.bold(true)
```

I expect the text should be bold, but it's not.

I noticed that to take effect, styles should be applied to `TextModel`, not `ParagraphModel`. Am I doing something wrong?

**Comment by jdugan** [comment]
I don't know what you mean by "from internal representation", so I'm not clear on what challenges the two syntactical options present to your program.  I do understand that you've simplified your example a great deal and so it's probably not a great illustration of your problem with DSL usage, but, taking it at face value, it looks pretty similar to the arguments-based syntax.  Maybe instead of trying to use the model setters, you could instead do something like the following:

```ruby
docx = Caracal::Document.new('test.docx')
options = {}
# populate the options hash from your data objects, application state, etc.
docx.p('Bold text', options)
```

**  The setters aren't technically private, but generally speaking, if you're interacting with Caracal models directly, you're engaging in a 5% use case reserved for experts who have read the source code thoroughly.  Said differently, the document methods exist precisely so that you don't need to understand the modeling Caracal choices Caracal makes.

**Comment by bolshakov** [comment]
Thanks, I changed by code to build options
