### ISSUE TITLE
Crashes if document generation starts in delayed job

### ISSUE THREAD

**Issue by anton-machkasov** [trade-informatics/caracal#90]
The problem is if export to docx works Ok with usual workflow, then the same code crashes with following error if it is running through delay job.

It crashes on parsing color. Did I miss anything or do you know already about that problem?

#<NoMethodError: undefined method `to_sym' for {"w:val"=>"333333"}:Hash>
"*/2.1.2/lib/ruby/gems/2.1.0/gems/term-ansicolor-1.2.2/lib/term/ansicolor/attribute.rb:45:in `get'"
"*/2.1.2/lib/ruby/gems/2.1.0/gems/term-ansicolor-1.2.2/lib/term/ansicolor/attribute.rb:40:in `[]'"

**Comment by jdugan** [comment]
Hei, Anton.

Based on the error message, the problem seems to be in the `term-ansicolor` gem.  That's not a dependency of Caracal (nor of any Caracal dependency, AFAIK).  Are you sure this is a Caracal problem and not related to some other aspect of your background job environment?

I don't think I've ever personally tried to create a Caracal document via a background job, but I can't think of any immediate reason that would fail to work the same way.  Can you put together a simple example repo that demonstrates the exact problem you are seeing?  Sort of the minimum configuration necessary to reproduce the problem?  I should be able to help you debug that.
