### ISSUE TITLE
Pop up download possible?

### ISSUE THREAD

**Issue by phagmann** [trade-informatics/caracal#93]
Hello,

I noticed that when I do something like "Caracal::Document.save 'example_ruby.docx' do |docx|...blahblah" to start my document write up inside ruby, it somehow magically appears in my commuter if i run the script. This, however, would be very confusing to most people who would use my eventual app and I couldn't find anything anywhere how to make it a "pop up download" as seen below ( I have a mac if that helps ). Any ideas or other gems that could possibly do this? Thanks in advance.

<img width="401" alt="screen shot 2018-05-09 at 8 55 25 pm" src="https://user-images.githubusercontent.com/13322177/39851395-66c0e86e-53cb-11e8-80ac-3d894cb032fe.png">

**Comment by jdugan** [comment]
Hi, Patrick.  

Thanks for the question.  It's hardly magic! :)  The `save` method just uses the standard `File` module in Ruby to write the contents of the Caracal document to disk. 

If you are using Caracal inside a Rails app, you might want to use [caracal-rails](https://github.com/trade-informatics/caracal-rails) and follow the design of the [example app](https://github.com/trade-informatics/caracal-example).  That design creates a standard "download a document" experience.  (Though the example app goes straight to the download link without presenting an HTML page with the link.)

If you prefer to handle everything directly, Caracal also has a `:render` [method](https://github.com/trade-informatics/caracal/blob/master/lib/caracal/document.rb#L74).  Save is really only for scripts where you want Caracal to create a document on the server's file system.  That's not super common these days, since most apps run in the cloud, where the file system is inaccessible.  In your case, `save` functions because your own machine is acting as the server.

**Comment by phagmann** [comment]
Hey Dugan,

Didn't expect such a quick response! I was having a hard time integrating the functionality of the example app into my current rails app. I couldn't figure out how you had rail's API connect to your show.docx.caracal file, mine only recognizes it if it's in show.html.erb or html.erb form rather. I'll experiment with the render method tonight! Ive been trying to figure out how to download a docx file with the press of a button. Also, I can't find a clean way to use rails to create a pop-up attachment download that would show the newly created file. My Ultimate goal is to use your gem to create a file with a simple press of a button. P.S. sorry if i'm being scatterbrained in my reply, I haven't had my coffee yet :)

**Comment by jdugan** [comment]
I live in Europe, so my speediness is probably just a function of timezones. :)

Huh.  The gem `caracal-rails` is really what's doing all the heavy lifting in the example project.  It takes care of hooking the `docx` format into Tilt for you, so Rails knows how to map the format type `docx` to `*.docx.caracal` templates automatically.  It also wraps your view templates in a Caracal render call so you only need to code the block part in the view template.  (Similar to how `prawnto` works vis-a-vis `prawn`.)  If you find Rails is trying to use the html format, you might try explicitly setting the format of the route to `:docx` to narrow the scope a bit.  Some browsers don't always send the right accepts headers, and in those cases, Rails defaults to HTML formatting unless the routing specifies otherwise.  (I think.)

I'm not sure I completely understand what you want to do ideally, but I'll say a couple things.  I do not believe you can configure your app so a user can click a link/button and open a new browser window __with the Caracal document loaded into it__.  The limitation there is the browser, not the library.  That's because the browser doesn't natively understand what the hell a `docx` file is the way it understands how to render a PNG or a PDF.  I believe you'll always have to set the disposition to `:attachment`, causing the file to be downloaded to the user's machine.  I think whether or not the browser asks you if that's okay first depends on your browser settings.

Having said all that, your basic use case of "user presses a button, the server makes a Word document on demand, and returns that file to the user" is exactly what Caracal is for.  It's the right library for the job.  Whatever is going wrong on your end is surmountable.  Keep fiddling and checking your work against the example project--you'll figure it out.

**Comment by phagmann** [comment]
I have a few things to try tonight! I think one of my mistakes was using the caracal gem instead of the caracel-rails gem, that could be whats going on. I was also having issues using the "send_data" built-in function, I might need to make sure all my formatting and paths are correct and the correct gems are installed. Thanks Again! I'll update you here if you care to hear it.

**Comment by phagmann** [comment]
Ajax was the culprit for whatever reason. It worked once I used window.location.href instead.

**Comment by jdugan** [comment]
Oh, sure.  An AJAX request would expect to get JSON back, right?  Caracal is always going to return the file contents.

I'm glad you got it sorted out.  I think Caracal will work great for what you want to do.  Good luck!
