### ISSUE TITLE
Add footnotes?

### ISSUE THREAD

**Issue by originalusername123** [trade-informatics/caracal#95]
Hello community! 

I totally love Caracal! The only thing that I can't find is creating footnotes, is this possible?

Thanks a lot!

**Comment by jdugan** [comment]
No, it's not.  

There's a long-standing desire to add header and footer support to Caracal, but so far no one--myself included--has implemented a complete solution to the problem.  The real issue is that headers and footers can accept any content the document body can.  So whatever solution is implemented isn't as simple as adding a directive for the one thing a given user needs.  (So, for example, the way I originally implemented page numbers is fundamentally the wrong approach.)

When Caracal was originally written, the project that spawned it didn't need headers and footers, so the library's design didn't include them at all.  Adding them properly will require significant changes to the DSL, the documentation, the modeling, and the rendering.  It would be a major bump.

You are, of course, welcome to take a crack at it.
