### ISSUE TITLE
Absolute Path For Created File Breaks

### ISSUE THREAD

**Issue by ifasoldt** [trade-informatics/caracal#99]
First of all, thanks for a lifesaver of a gem! Saves me trying to do something terrible like creating a pdf and using a pdf to word converter.

I am having one issue however.

When trying to save a file like so:
`directory_path = "#{Rails.root.to_s}/AppConfig.some_directory_path"`
`document_path = directory_path + "/document_name.docx`

`Caracal::Document.save docx_file_path do |docx|`

I get the following error:"

`No such file or directory @ rb_sysopen - .//Users/ifasoldt/Documents/app_root/some_directory/document_name.docx`

It seems that the gem is taking the path given to it, whether relative or absolute, and appending it to `./`. 

Absolute paths are safer and easier (at least for me), especially when deploying into a different environment where the file structure may be different that one's local environment. It would be nice to be able to use absolute paths with the gem.

**Comment by ifasoldt** [comment]
If you would like, I can probably make a PR for the issue and submit, I just want to make sure that I am not missing a way to configure this.

**Comment by jdugan** [comment]
Hi.  First, thanks for the kind words.  It's always nice to hear the library helped someone.

I think the original implementation assumed the name attribute was a bare name (e.g., my_file.docx).  That's why it appends the `./`to convert the name value to a path.  

Having written that, I don't think there's any good reason why Caracal couldn't accept a path here, as long as we preserve the current behaviour to prevent backward compatibility issues for other users.  So, if the user provides a bare name, we append the current directory notation; otherwise, we don't.  That sort of thing.  Would that work for you?

Thoughtfully authored PRs are always welcome. :)

**Comment by ifasoldt** [comment]
sounds good, I'll submit a pr when I have time!

**Comment by jdugan** [comment]
I'm at a hackathon thing tonight, so I decided to work on a few Caracal items.  Yours was one of them.  I've released v1.4.0, which should allow you to add any kind of reasonable path string in the document name.  

Let me know if you run into any issues.  Cheers!
